{% set name = "pyerrors" %}
{% set version = "2.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyerrors-{{ version }}.tar.gz
  sha256: a058a7ddc7ee9e1a5efbb88b8ac3c317290d7138d0f08f78273ee882e842faf1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=63.0.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.21
    - autograd >=1.5
    - numdifftools >=0.9.41
    - matplotlib-base >=3.5
    - scipy >=1.7
    - iminuit >=2.17
    - h5py >=3.8
    - lxml >=4.9
    - python-rapidjson >=1.9
    - pandas >=1.1

test:
  imports:
    - pyerrors
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/fjosw/pyerrors
  summary: Error propagation and statistical analysis for Monte Carlo simulations
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
    - fjosw
    - s-kuberski
