{% set name = "pyerrors" %}
{% set version = "2.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyerrors-{{ version }}.tar.gz
  sha256: c976fde1f0a543e85b46a575986f7364c69f120daff866edb689d38af835ed7e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=63.0.0
    - wheel
    - pip
  run:
    - python >=3.7
    - numpy >=1.21
    - autograd >=1.5
    - numdifftools >=0.9.41
    - matplotlib-base >=3.5
    - scipy >=1.7
    - iminuit >=2.17
    - h5py >=3.8
    - lxml >=4.9
    - python-rapidjson >=1.9
    - pandas >=1.1

test:
  imports:
    - pyerrors
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fjosw/pyerrors
  summary: Error propagation and statistical analysis for Monte Carlo simulations
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
    - fjosw
    - s-kuberski
